baseURL = "https://newcastlecybersecurity.group/"
languageCode = "en-uk"
title = "Newcastle Cyber Security Group"
publishDir = "../public"
pygmentsStyle = "atom"
pygmentsUseClasses = true
enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS"]

[params]
mainSections = ["presentations", "snippets"]

[markup.goldmark.renderer]
unsafe= true
